import "./globals.css";
import Topo from '@/app/components/Topo';

export const metadata = {
  title: "Agencia de Design Digital M.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
